#!/bin/sh

#-- Internal variables
PPP_DIR="/etc/ppp"

# ------------------------------------------------------------- #
# --------------- [ Main Procedure ] -------------------------- #
# ------------------------------------------------------------- #
# Parse command line arguments
case "$1" in
    ppp0)
        . $PPP_DIR/session1-up
        ;;
    ppp1)
        . $PPP_DIR/session2-up
        ;;
    *)
        exit 1
        ;;
esac
